services:
  app:
    build:
      dockerfile: Dockerfile
    command: >
      gunicorn --bind 0.0.0.0:8000
      --workers 2
      --timeout 120
      --worker-class sync
      mysite.wsgi:application
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-file: '2'
        max-size: '200k'
    volumes:
      - ./mysite/database:/app/database
