# Generated by Django 5.2.7 on 2026-01-25 19:34
from django.contrib.auth.models import User
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(default=User.username, max_length=100),
        ),
    ]
